### ISSUE TITLE
Column 9 is unresponsive

### ISSUE THREAD

**Issue by hillam** [hillam/EasyAVR-Tada68#1]
At the time of writing this, everything seems to work so far except for column 9 (8, I, K, M), which is unresponsive. I copied the row and column config from @TerryMathews' QMK [`config.h`](https://github.com/qmk/qmk_firmware/blob/master/keyboards/tada68/config.h#L37):
```c
#define MATRIX_ROW_PINS {D0,D1,F6,F7,D5}
#define MATRIX_COL_PINS {F0,F1,E6,C7,C6,B7,D4,B1,B0,B5,B4,D7,D6,B3,F4}
``` 

[mine](https://github.com/hillam/EasyAVR-Tada68/blob/master/boards/tada68.py#L80):
```python
rows=[D0, D1, F6, F7, D5],
cols=[F0, F1, E6, C7, C6, B7, D4, B1, B0, B5, B4, D7, D6, B3, F4]
```

I've double and triple checked [my matrix](https://github.com/hillam/EasyAVR-Tada68/blob/master/boards/tada68.py#L143) against the [QMK one](https://github.com/qmk/qmk_firmware/blob/master/keyboards/tada68/tada68.h#L25) as well, and I believe I have everything the same. I've wondered if my backlighting configuration (I haven't really changed that from the template I started with yet) may have something to do with this problem.

I'd like to shoutout to @TerryMathews and @dhowland in hopes of getting some more knowledgeable eyes on this to help me out.

**Comment by TerryMathews** [comment]
From your tada68.py line 112: led_hardware = [
# Port Pin Direction
( REF_PORTB, 6, LED_DRIVER_PULLUP ),
( REF_PORTB, 7, LED_DRIVER_PULLUP )
Tada68 doesn't have Scroll Lock. It has backlight and Caps Lock. So I
believe it should be (and apologies, I've never used Easy AVR...)

led_definition = [
('Caps Key', 'Caps Lock'),
('Backlight Key', 'Backlight')
]
# Definition of LED pins. (indicators and backlights) Indicators
# must come first and be in the same order as defined in led_definition.
# LED_DRIVER_PULLUP is used when the pin is connected to the anode of
# the LED and the cathode is connected to ground.
# LED_DRIVER_PULLDOWN is used when the pin is connected to the cathode
# of the LED and the anode is connected to the power supply.
led_hardware = [
# Port Pin Direction
( REF_PORTB, 2, LED_DRIVER_PULLUP ),
( REF_PORTB, 6, LED_DRIVER_PULLUP )
] It's possible those should be LED_DRIVER_PULLDOWN instead of pullup, just
try it and reverse it if it's not working right.

**Comment by hillam** [comment]
@TerryMathews that did the trick! Interestingly pullup/pulldown didn't make any difference, but the settings you posted did the trick 100%! I was pretty clueless on the backlighting portion and was somewhat suspicioius that it could break the rest of the config somehow. Thank you so much!

**Comment by dhowland** [comment]
Yeah, @TerryMathews got it.  You were configuring the LED code to use the same pin (B7) as the Matrix code.

Pullup/Pulldown definitely makes a difference for the LED support.  If it's incorrect then you would notice it right away, so if your keyboard seems to be working, then I'd say you're done.

**Comment by hillam** [comment]
@dhowland thanks for responding. I think I tried it with both PULLUP and PULLDOWN and didn't notice any difference, so maybe I was missing something. I'd like to put together a pull request to incorporate EasyAVR later this week. Do you have any tips or suggestions you'd like to add before I do that? Thanks again.

**Comment by TerryMathews** [comment]
Pullup/pulldown is going to manifest as LEDs in the wrong state (off but
should be on, vice versa).

Since the backlight is controlled as a toggle, you can't really do much
with it. Caps lock, you should be checking the board indicator against the
Windows state. You could use a program like Switch Hitter, or you could
just type something.

**Comment by hillam** [comment]
Ah, that makes sense. I'll play around with it a bit more later to make sure I have it right. Thanks.
